/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, '') || 'https://www.mallareddyschool.com',
  generateRobotsTxt: false, // robots.txt is generated by src/app/robots.ts
  outDir: 'public',
  changefreq: 'monthly',
  priority: 0.7,
  sitemapSize: 5000,
  // /blog/[slug] dynamic routes are added manually via generate-sitemap.mjs
  exclude: ['/api/*', '/robots.txt', '/icon.svg'],
  transform: async (config, path) => {
    return {
      loc: path,
      changefreq:
        path === '/' || path === '/admission' || path === '/contact'
          ? 'weekly'
          : config.changefreq,
      priority:
        path === '/' || path === '/admission'
          ? 1.0
          : path === '/contact' || path === '/blog'
          ? 0.9
          : config.priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
      alternateRefs: config.alternateRefs ?? [],
    };
  },
};
